# fly.toml app configuration file generated for tsi-products on 2023-09-01T11:01:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsi-products"
primary_region = "scl"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
