// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Business.Persistence;

#nullable disable

namespace Products.Business.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240323162103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Products.Business.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Brand Azul",
                            Color = 2,
                            Name = "Product Azul"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Brand Rojo",
                            Color = 0,
                            Name = "Product Rojo"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Brand Verde",
                            Color = 1,
                            Name = "Product Verde"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Brand Azul #2",
                            Color = 2,
                            Name = "Product Azul #2"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Brand Rojo #2",
                            Color = 0,
                            Name = "Product Rojo #2"
                        });
                });

            modelBuilder.Entity("Products.Business.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
